BilleniumNotes/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BilleniumNotes.Models
{
    public class Note
    {
        
        public int Id { get; set; }
        public string AuthorID { get; set; }
        //public List<int> Rates = new List<int>();

        public double Average { get; set; }

        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Lecturer { get; set; }
        [Required]
        public string Subject { get; set; }
        //public int SelectedDepartmentId { get; set; }
        //public SelectList DepList { get; set; }

        //public int RatingSelected { get; set; }

        [Required]
        public string  Department { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }

        public string TextShort
        {
            get
            {
                if (Description.Length > 30)
                    return Description.Substring(0, 30) + "...";
                else
                    return Description;
            }
        }

    }

    public class NotesDBContext : DbContext
    {
        public DbSet<Note> Notes { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Rating> Ratings { get; set; }
    }
}

BilleniumNotes/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BilleniumNotes.Models;
using System.IO;
using System.Globalization;

namespace BilleniumNotes.Controllers
{
    public class NotesController : Controller
    {
        private NotesDBContext db = new NotesDBContext();

        // GET: Notes
        public ActionResult Index()
        {
            return View(db.Notes.ToList());
        }

        public ActionResult MyNotes()
        {
            var userID = Microsoft.AspNet.Identity.IdentityExtensions.GetUserId(User.Identity);
            return View(db.Notes.Where(o=>o.AuthorID == userID).ToList());
        }

        // GET: Notes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // GET: Notes/Create
   
        public ActionResult Create()
        {
            ViewBag.InsigniaList = new SelectList(db.Departments.AsEnumerable(), "Id", "Name", 1);
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Note note, HttpPostedFileBase FileUpload)
        {
            DepartmentsController connect = new DepartmentsController();
            //note.Department = connect.GetDepartment(note.insignia);
            //ModelState.SetModelValue("Department", new ValueProviderResult(note.Department, note.Department.Id.ToString(), CultureInfo.CurrentCulture));
            if (ModelState.IsValid && FileUpload != null)
            {
                var userID = Microsoft.AspNet.Identity.IdentityExtensions.GetUserId(User.Identity);
                note.AuthorID = userID;
                db.Notes.Add(note);
                db.SaveChanges();
                UploadNote(note.Id, FileUpload);
                return RedirectToAction("Index");
            }
            ViewBag.InsigniaList = new SelectList(db.Departments.AsEnumerable(), "Id", "Name", 1);
            return View(note);
        }

        public FileResult DownloadNote(int id)
        {
            string path = Path.Combine(Server.MapPath("~/UploadUsers/NotesAttachements/" + id));
            string[] files = Directory.GetFiles(path);
            string filePath = files.FirstOrDefault();
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
            var response = new FileContentResult(fileBytes, filePath);
            response.FileDownloadName = Path.GetFileName(filePath);
            return response;
        }
        private void UploadNote(int id, HttpPostedFileBase file)
        {
            var pathDir = Server.MapPath("~/UploadUsers/NotesAttachements/"+ id.ToString());
            var path = Path.Combine(Server.MapPath("~/UploadUsers/NotesAttachements/" + id.ToString()), Path.GetFileName(file.FileName));
            Directory.CreateDirectory(pathDir);
            file.SaveAs(path);
        }

        // GET: Notes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Average,Title,Description")] Note note)
        {
            if (ModelState.IsValid)
            {
                db.Entry(note).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Note note = db.Notes.Find(id);
            db.Notes.Remove(note);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BilleniumNotes/Controllers/RatingController.cs
using BilleniumNotes.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static BilleniumNotes.Models.Note;
using Microsoft.AspNet.Identity;

namespace BilleniumNotes.Controllers
{
    [Authorize]
    public class RatingController : Controller
    {
        private NotesDBContext db = new NotesDBContext();
        
        public double FullStarsToShow(int NoteID)
        {
            //double avr = GetAverage(NoteID);
            double avr = db.Notes.Find(NoteID).Average;
            double y = avr - Math.Floor(avr);
            return avr - y;
        }
        public int OffsetStarToShow(int NoteID)
        {
            //double avr = GetAverage(NoteID);
            double avr = db.Notes.Find(NoteID).Average;
            double x = avr - Math.Floor(avr);
            if (x == 0)
                return 0;
            if (x < 0.26)
                return 1;
            if (x < 0.51)
                return 2;
            if (x < 0.76)
                return 3;
            else
                return 0;
        }

        public double EmptyStarsToShow(int NoteID)
        {
            double x = 5 - FullStarsToShow(NoteID);
            if (OffsetStarToShow(NoteID) != 0)
                x--;
            return x;
        }
        public double GetAverage(int NoteID)
        {
            double avr = 0;
            double suma = GetRatingsValueSum(NoteID);
            double ilosc = GetRatingsCount(NoteID);
            if(ilosc != 0)
                avr = suma / ilosc;
            return avr;
        }

        public double GetRatingsCount(int NoteID)
        {
            Note note = db.Notes.Find(NoteID);
            try
            {
                List<Rating> rats = db.Ratings.Where(o => o.NoteID == NoteID).ToList();
                return rats.Count;
            }
            catch
            {
                return 0;
            }
        }

        public double GetRatingsValueSum(int NoteID)
        {
            double value = 0;
            Note note = db.Notes.Find(NoteID);
            try
            {
                List<Rating> rats = db.Ratings.Where(o => o.NoteID == NoteID).ToList();
                foreach (Rating rate in rats)
                {
                    value += rate.RatingValue;
                }
            }
            catch
            {
                value = 0;
            }
            return value;
        }
        [HttpGet]
        public bool AddRating(int rate,int NoteID)
        {
            Note note = db.Notes.Find(NoteID);
            //var userID = Microsoft.AspNet.Identity.UserManagerExtensions.FindById(User.Identity.GetUserId());
            var userID = Microsoft.AspNet.Identity.IdentityExtensions.GetUserId(User.Identity);
            //Rating rating = note.Ratings.Where(o => o.UserID == userID).FirstOrDefault();
            Rating rating = db.Ratings.Where(o => o.UserID == userID && o.NoteID == NoteID).FirstOrDefault();
            if (rating == null)
            {
                Rating r = new Rating() { UserID = userID, NoteID = note.Id, RatingValue = rate };
                db.Ratings.Add(r);
                db.SaveChanges();
            }
            else
            {
                rating.RatingValue = rate;
                db.SaveChanges();
            }
            note.Average = GetAverage(note.Id);
            db.SaveChanges();
            return true;
        }

    }
}

BilleniumNotes/Views/Notes/Create.cshtml
@model BilleniumNotes.Models.Note
    
@{
    ViewBag.Title = "Utwórz notatkę";
    List<BilleniumNotes.Models.Department> DepartamentListOld = new BilleniumNotes.Controllers.DepartmentsController().GetDepartments();
    IEnumerable<SelectListItem> DepartamentSelectList = DepartamentListOld.Select(x => new SelectListItem() { Text = x.Name.Trim(), Value = x.Id.ToString()});
    //IEnumerable<SelectListItem> DepartamentSelectList = DepartamentList as IEnumerable<SelectListItem>;
}

<h2>@ViewBag.Title</h2>

<center>
    @using (Html.BeginForm("Create", "Notes", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Tytuł" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { size = 100, @class = "form-control", @placeholder = "Opis" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="">
                    @Html.EditorFor(model => model.Lecturer, new { htmlAttributes = new { @class = "form-control", @placeholder = "Wykładowca" } })
                    @Html.ValidationMessageFor(model => model.Lecturer, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="">
                    @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control", @placeholder = "Przedmiot" } })
                    @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    @Html.DropDownListFor(model => model.Department, (SelectList)ViewBag.InsigniaList, "Oddział")
                </div>
            </div>
            <div class="form-group">
                <div class="">
                    <label for="thumbnail">Załącznik</label>
                    <input type="file" id="FileUpload" name="FileUpload" accept="image/*, text/plain, .pdf, .rar, .zip" class="btn btn-default" />
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</center>
<div>
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BilleniumNotes/Views/Notes/Delete.cshtml
@model BilleniumNotes.Models.Note

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Average)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Average)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BilleniumNotes/Views/Notes/Details.cshtml
@model BilleniumNotes.Models.Note

@{
    ViewBag.Title = "Szczegóły ogłoszenia";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Average)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Average)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    
    <a onclick="history.go(-1); return false;" href="#">Back to list</a><br />
    
</p>

BilleniumNotes/Views/Notes/Edit.cshtml
@model BilleniumNotes.Models.Note

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Note</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Average, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Average, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Average, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BilleniumNotes/Views/Notes/Index.cshtml
@model IEnumerable<BilleniumNotes.Models.Note>

@{
    ViewBag.Title = "Lista notatek";
    List<BilleniumNotes.Models.Department> DepartamentList = new BilleniumNotes.Controllers.DepartmentsController().GetDepartments();
    BilleniumNotes.Controllers.RatingController rC = new BilleniumNotes.Controllers.RatingController();
    List<int> RatingsValues = new List<int>() { 0, 1, 2, 3, 4, 5 };
    IEnumerable<SelectListItem> RatingsSelectList = RatingsValues.Select(x => new SelectListItem() { Text = x.ToString(), Value = x.ToString() });
}


<h2>@ViewBag.Title</h2>


<table class="table">
    <tr>
        <th>
            Ocena
        </th>
        <th>
            Tytuł
        </th>
        <th>
            Opis
        </th>
        <th>
            Wydział
        </th>
        <th>
            Opcje
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td class="starIcons">
            @*@Html.DisplayFor(modelItem => item.Average)*@
            @{
                var Fulls = rC.FullStarsToShow(item.Id);
                var Offset = rC.OffsetStarToShow(item.Id);
                var Emptys = rC.EmptyStarsToShow(item.Id);
                for (var i = 0; i < Fulls; i++)
                {
                    <img src="@Url.Content("~/Images/star4.png")" />
                }
                switch (Offset)
                {
                    case 1:
                        <img src="@Url.Content("~/Images/star1.png")" />
                        break;
                    case 2:
                        <img src="@Url.Content("~/Images/star2.png")" />
                        break;
                    case 3:
                        <img src="@Url.Content("~/Images/star3.png")" />
                        break;
                }
                for (var i = 0; i < Emptys; i++)
                {
                    <img src="@Url.Content("~/Images/star0.png")" />
                }
            }
            <br />
            <center><button type="button" class="btn btn-link btn-sm" data-toggle="modal" data-target="#myModal" onclick="SetModalValues(this)" data-assigned-id="@item.Id">Oceń</button></center>
           
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td >
                @Html.DisplayFor(modelItem => item.Description)
        </td>
        <th>
                @Html.DisplayFor(modelItem => DepartamentList[Convert.ToInt32(item.Department) - 1].Name)
        </th>
        <td>
            @Html.ActionLink("Szczegóły", "Details", new { id=item.Id }) |
            @Html.ActionLink("Załącznik" , "DownloadNote", new { id = item.Id }, new { @class = "btn btn-default" })
        </td>
    </tr>
}

</table>

<script>
    function SetModalValues(elem) {
        var valueId =  $(elem).attr('data-assigned-id');
        $("#setId").attr("data-assigned-id", valueId);
    }
     
                function AssignButtonClicked(elem) {
                    var id = $(elem).data('assigned-id');
                    var url = '@Url.Action("AddRating", "Rating", new { rate = "-------", NoteID ="tttttttt"}, null)';
                    url = url.replace("-------", $('#ParticipantList').val());
                    url = url.replace("tttttttt", id);
                    url = url.replace("&amp;", "&")

                    $.ajax({
                        url: url, // comma here instead of semicolon
                        success: function () {
                            //alert("Value Added");  // or any other indication if you want to show
                        }

                    });
                    //window.location = url;
                }

</script>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header btn-primary">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Oceń notatkę</h4>
            </div>
            <div class="modal-body">
                <center>@Html.DropDownList("ParticipantList", RatingsSelectList, new { @class = "form-control" })</center>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Zamknij</button>
                <button type="button" id="setId"  class="btn btn-primary" onclick="AssignButtonClicked(this)" data-assigned-id="" data-dismiss="modal">Oceń</button>
                @*<button type="button" onclick="saveChanges()" >Zaakceptuj</button>*@
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

BilleniumNotes/Views/Notes/MyNotes.cshtml
@model IEnumerable<BilleniumNotes.Models.Note>

@{
    ViewBag.Title = "Moje ogłoszenia";
    List<BilleniumNotes.Models.Department> DepartamentList = new BilleniumNotes.Controllers.DepartmentsController().GetDepartments();
    BilleniumNotes.Controllers.RatingController rC = new BilleniumNotes.Controllers.RatingController();
    List<int> RatingsValues = new List<int>() { 0, 1, 2, 3, 4, 5 };
    IEnumerable<SelectListItem> RatingsSelectList = RatingsValues.Select(x => new SelectListItem() { Text = x.ToString(), Value = x.ToString() });
}


<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
           Ocena
        </th>
        <th>
          Tytuł
        </th>
        <th>
           Opis
        </th>
        <th>
           Wydział
        </th>
        <th>
            Opcje
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @*@Html.DisplayFor(modelItem => item.Average)*@
                @{
                    var Fulls = rC.FullStarsToShow(item.Id);
                    var Offset = rC.OffsetStarToShow(item.Id);
                    var Emptys = rC.EmptyStarsToShow(item.Id);
                    for (var i = 0; i < Fulls; i++)
                    {
                        <img src="@Url.Content("~/Images/star4.png")" />
                    }
                    switch (Offset)
                    {
                        case 1:
                            <img src="@Url.Content("~/Images/star1.png")" />
                            break;
                        case 2:
                            <img src="@Url.Content("~/Images/star2.png")" />
                            break;
                        case 3:
                            <img src="@Url.Content("~/Images/star3.png")" />
                            break;
                    }
                    for (var i = 0; i < Emptys; i++)
                    {
                        <img src="@Url.Content("~/Images/star0.png")" />
                    }
                }
                <br />
                <center><button type="button" class="btn btn-link btn-sm" data-toggle="modal" data-target="#myModal" onclick="SetModalValues(this)" data-assigned-id="@item.Id">Oceń</button></center>

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <th>
                @Html.DisplayFor(modelItem => DepartamentList[Convert.ToInt32(item.Department) - 1].Name)
            </th>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Szczegóły", "Details", new { id = item.Id }) |
                @Html.ActionLink("Usuń", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Załącznik", "DownloadNote", new { id = item.Id }, new { @class = "btn btn-default" })
            </td>
        </tr>
                    }

</table>

<script>
    function SetModalValues(elem) {
        var valueId =  $(elem).attr('data-assigned-id');
        $("#setId").attr("data-assigned-id", valueId);
    }

                function AssignButtonClicked(elem) {
                    var id = $(elem).data('assigned-id');
                    var url = '@Url.Action("AddRating", "Rating", new { rate = "-------", NoteID ="tttttttt"}, null)';
                    url = url.replace("-------", $('#ParticipantList').val());
                    url = url.replace("tttttttt", id);
                    url = url.replace("&amp;", "&")

                    $.ajax({
                        url: url, // comma here instead of semicolon
                        success: function () {
                            //alert("Value Added");  // or any other indication if you want to show
                        }

                    });
                    //window.location = url;
                }

</script>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header btn-primary">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Oceń notatkę</h4>
            </div>
            <div class="modal-body">
                <center>@Html.DropDownList("ParticipantList", RatingsSelectList, new { @class = "form-control" })</center>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Zamknij</button>
                <button type="button" id="setId" class="btn btn-primary" onclick="AssignButtonClicked(this)" data-assigned-id="" data-dismiss="modal">Oceń</button>
                @*<button type="button" onclick="saveChanges()" >Zaakceptuj</button>*@
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>